# -*- coding: utf-8 -*-
"""access.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBzvnbEVbEKslGxkJLYX89ljwe7vQ_vK
"""

import osmnx as ox
import geopandas as gpd

def get_poi_data(place_name, amenity_type):
    """
    Fetch OpenStreetMap points of interest (schools or hospitals)
    and return as GeoDataFrame.
    """
    gdf = ox.geometries_from_place(place_name, tags={'amenity': amenity_type})
    gdf = gdf[['geometry', 'name']].reset_index()
    return gdf

def load_population_data(file_path):
    """
    Load population dataset (census or WorldPop) as GeoDataFrame.
    """
    pop_gdf = gpd.read_file(file_path)
    return pop_gdf