# -*- coding: utf-8 -*-
"""assess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBzvnbEVbEKslGxkJLYX89ljwe7vQ_vK
"""

import numpy as np
from scipy.stats import bernoulli, norm

def bernoulli_access(distances, threshold_km):
    """
    Compute Bernoulli probabilities for households within threshold distance.
    distances: np.array of distances in km
    """
    return bernoulli.rvs(distances <= threshold_km)

def gaussian_distance_analysis(distances):
    """
    Compute mean, std, and PDF of distances assuming Gaussian distribution.
    """
    mu, sigma = np.mean(distances), np.std(distances)
    pdf = norm.pdf(distances, mu, sigma)
    return mu, sigma, pdf

def bayesian_regression(X, y):
    """
    Placeholder for Bayesian regression to predict number of facilities
    based on population density.
    Replace with pymc or other Bayesian framework later.
    """
    # Example: return simple linear regression for now
    coef = np.linalg.lstsq(X, y, rcond=None)[0]
    return coef