# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBzvnbEVbEKslGxkJLYX89ljwe7vQ_vK
"""

def km_to_miles(km):
    return km * 0.621371

def miles_to_km(miles):
    return miles / 0.621371